afsutil: check for bosserver error on startup
Bail and return an error in the transarc mode server init script when
the bosserver fails to start.  This will cause 'afsutil start server' to
fail with an error when the bosserver fails to start.

Note: Currently the bosserver will exit with 0 when started with an
unrecognized option, so this change to the init script is only useful
for other errors until the bosserver is fixed.

diff --git a/libraries/afsutil/afsutil/data/openafs-server.init b/libraries/afsutil/afsutil/data/openafs-server.init
--- a/libraries/afsutil/afsutil/data/openafs-server.init
+++ b/libraries/afsutil/afsutil/data/openafs-server.init
@@ -1,6 +1,6 @@
 #!/bin/bash
 #
-# Copyright (c) 2014-2015, Sine Nomine Associates
+# Copyright (c) 2014-2017, Sine Nomine Associates
 #
 # Redistribution and use in source and binary forms, with or without
 # modification, are permitted provided that the following conditions are met:
@@ -54,6 +54,10 @@ start() {
         if test -x $BOSSERVER ; then
             echo "Starting AFS servers..... "
             $BOSSERVER $BOSSERVER_OPTIONS
+            if [ $? -ne 0 ]; then
+                echo "Failed to start bosserver!"
+                exit 1
+            fi
             test "$afs_rh" && touch /var/lock/subsys/openafs-server
             if is_on $WAIT_FOR_SALVAGE; then
                 sleep 10
